# Generated by Django 4.1.3 on 2022-11-15 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patientdetails',
            fields=[
                ('pat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pat_name', models.CharField(max_length=50)),
                ('problem', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='admissiondetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doj', models.DateField()),
                ('pat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosdata.patientdetails')),
            ],
        ),
    ]
