# Generated by Django 4.1.3 on 2022-11-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='casesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
                ('patientName', models.CharField(max_length=50)),
                ('disease', models.CharField(max_length=50)),
                ('doctorName', models.CharField(max_length=50)),
                ('primaryCheck', models.CharField(max_length=3)),
                ('Consultation', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Primary', 'Admitted'), ('Discharged', 'Discharged')], default='Primary', max_length=15)),
                ('referance', models.CharField(max_length=50)),
            ],
        ),
    ]
