# Generated by Django 4.1.3 on 2022-11-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casesheet',
            name='status',
            field=models.CharField(choices=[('Primary', 'Admitted'), ('Discharged', 'Discharged'), ('Consultation', 'Consultation')], default='Primary', max_length=15),
        ),
    ]
