# Generated by Django 4.1.3 on 2022-11-10 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientinfo', '0002_alter_casesheet_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casesheet',
            old_name='Consultation',
            new_name='Consultationfee',
        ),
    ]
