# Generated by Django 4.1.3 on 2022-11-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientinfo', '0004_finalcasesheet_remove_casesheet_id_casesheet_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casesheet',
            name='pid',
        ),
        migrations.AddField(
            model_name='casesheet',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
