# Generated by Django 4.1.3 on 2022-11-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientinfo', '0006_delete_finalcasesheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casesheet',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
