# Generated by Django 4.1.3 on 2022-11-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientinfo', '0007_alter_casesheet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casesheet',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
