# Generated by Django 4.1.3 on 2022-11-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientinfo', '0008_alter_casesheet_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='finalcasesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientName', models.CharField(max_length=50)),
                ('doc', models.DateField()),
                ('medicines', models.TextField()),
                ('finalstatus', models.CharField(choices=[('Primary', 'Admitted'), ('Discharged', 'Discharged'), ('Consultation', 'Consultation')], default='Primary', max_length=15)),
                ('remarks', models.TextField()),
            ],
        ),
    ]
