# Generated by Django 4.1.3 on 2022-11-10 11:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patientinfo', '0009_finalcasesheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casesheet',
            name='id',
        ),
        migrations.AddField(
            model_name='casesheet',
            name='patient_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='finalcasesheet',
            name='pat_id',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='patientinfo.casesheet'),
        ),
    ]
